<OPTION VALUE=""></OPTION>
<OPTION CLASS=NavLeftHighlight1 VALUE="">-- <%=Translate("Outside United States and Canada",Login_Language,conn)%></OPTION>
<OPTION Class=Region3 VALUE="ZZ" <% if SVALUE = "ZZ" then response.write "SELECTED" %>>N/A</OPTION>
<OPTION VALUE=""></OPTION>
<OPTION Class=NavLeftHighlight1 VALUE="">-- United States</OPTION>
<OPTION CLASS=Region1 VALUE="AL" <% if SVALUE = "AL" then response.write "SELECTED" %>>AL - Alabama</OPTION>
<OPTION CLASS=Region1 VALUE="AK" <% if SVALUE = "AK" then response.write "SELECTED" %>>AK - Alaska</OPTION>
<OPTION CLASS=Region1 VALUE="AZ" <% if SVALUE = "AZ" then response.write "SELECTED" %>>AZ - Arizona</OPTION>
<OPTION CLASS=Region1 VALUE="AR" <% if SVALUE = "AR" then response.write "SELECTED" %>>AR - Arkansas</OPTION>
<OPTION CLASS=Region1 VALUE="CA" <% if SVALUE = "CA" then response.write "SELECTED" %>>CA - California</OPTION>
<OPTION CLASS=Region1 VALUE="CO" <% if SVALUE = "CO" then response.write "SELECTED" %>>CO - Colorado</OPTION>
<OPTION CLASS=Region1 VALUE="CT" <% if SVALUE = "CT" then response.write "SELECTED" %>>CT - Conneticut</OPTION>
<OPTION CLASS=Region1 VALUE="DE" <% if SVALUE = "DE" then response.write "SELECTED" %>>DE - Delaware</OPTION>
<OPTION CLASS=Region1 VALUE="DC" <% if SVALUE = "DC" then response.write "SELECTED" %>>DC - District of Columbia</OPTION>
<OPTION CLASS=Region1 VALUE="FL" <% if SVALUE = "FL" then response.write "SELECTED" %>>FL - Florida</OPTION>
<OPTION CLASS=Region1 VALUE="GA" <% if SVALUE = "GA" then response.write "SELECTED" %>>GA - Georgia</OPTION>
<OPTION CLASS=Region1 VALUE="HI" <% if SVALUE = "HI" then response.write "SELECTED" %>>HI - Hawaii</OPTION>
<OPTION CLASS=Region1 VALUE="ID" <% if SVALUE = "ID" then response.write "SELECTED" %>>ID - Idaho</OPTION>
<OPTION CLASS=Region1 VALUE="IL" <% if SVALUE = "IL" then response.write "SELECTED" %>>IL - Illinois</OPTION>
<OPTION CLASS=Region1 VALUE="IN" <% if SVALUE = "IN" then response.write "SELECTED" %>>IN - Indiana</OPTION>
<OPTION CLASS=Region1 VALUE="IA" <% if SVALUE = "IA" then response.write "SELECTED" %>>IA - Iowa</OPTION>
<OPTION CLASS=Region1 VALUE="KS" <% if SVALUE = "KS" then response.write "SELECTED" %>>KS - Kansas</OPTION>
<OPTION CLASS=Region1 VALUE="KY" <% if SVALUE = "KY" then response.write "SELECTED" %>>KY - Kentucky</OPTION>
<OPTION CLASS=Region1 VALUE="LA" <% if SVALUE = "LA" then response.write "SELECTED" %>>LA - Louisiana</OPTION>
<OPTION CLASS=Region1 VALUE="ME" <% if SVALUE = "ME" then response.write "SELECTED" %>>ME - Maine</OPTION>
<OPTION CLASS=Region1 VALUE="MD" <% if SVALUE = "MD" then response.write "SELECTED" %>>MD - Maryland</OPTION>
<OPTION CLASS=Region1 VALUE="MA" <% if SVALUE = "MA" then response.write "SELECTED" %>>MA - Massachusetts</OPTION>
<OPTION CLASS=Region1 VALUE="MI" <% if SVALUE = "MI" then response.write "SELECTED" %>>MI - Michigan</OPTION>
<OPTION CLASS=Region1 VALUE="MN" <% if SVALUE = "MN" then response.write "SELECTED" %>>MN - Minnesota</OPTION>
<OPTION CLASS=Region1 VALUE="MS" <% if SVALUE = "MS" then response.write "SELECTED" %>>MS - Mississippi</OPTION>
<OPTION CLASS=Region1 VALUE="MO" <% if SVALUE = "MO" then response.write "SELECTED" %>>MO - Missouri</OPTION>
<OPTION CLASS=Region1 VALUE="MP" <% if SVALUE = "MP" then response.write "SELECTED" %>>MP - Northern Mariana Islands</OPTION>
<OPTION CLASS=Region1 VALUE="MT" <% if SVALUE = "MT" then response.write "SELECTED" %>>MT - Montana</OPTION>
<OPTION CLASS=Region1 VALUE="NE" <% if SVALUE = "NE" then response.write "SELECTED" %>>NE - Nebraska</OPTION>
<OPTION CLASS=Region1 VALUE="NV" <% if SVALUE = "NV" then response.write "SELECTED" %>>NV - Nevada</OPTION>
<OPTION CLASS=Region1 VALUE="NH" <% if SVALUE = "NH" then response.write "SELECTED" %>>NH - New Hampshire</OPTION>
<OPTION CLASS=Region1 VALUE="NJ" <% if SVALUE = "NJ" then response.write "SELECTED" %>>NJ - New Jersey</OPTION>
<OPTION CLASS=Region1 VALUE="NM" <% if SVALUE = "NM" then response.write "SELECTED" %>>NM - New Mexico</OPTION>
<OPTION CLASS=Region1 VALUE="NY" <% if SVALUE = "NY" then response.write "SELECTED" %>>NY - New York</OPTION>
<OPTION CLASS=Region1 VALUE="NC" <% if SVALUE = "NC" then response.write "SELECTED" %>>NC - North Carolina</OPTION>
<OPTION CLASS=Region1 VALUE="ND" <% if SVALUE = "ND" then response.write "SELECTED" %>>ND - North Dakota</OPTION>
<OPTION CLASS=Region1 VALUE="OH" <% if SVALUE = "OH" then response.write "SELECTED" %>>OH - Ohio</OPTION>
<OPTION CLASS=Region1 VALUE="OK" <% if SVALUE = "OK" then response.write "SELECTED" %>>OK - Oklahoma</OPTION>
<OPTION CLASS=Region1 VALUE="OR" <% if SVALUE = "OR" then response.write "SELECTED" %>>OR - Oregon</OPTION>
<OPTION CLASS=Region1 VALUE="PA" <% if SVALUE = "PA" then response.write "SELECTED" %>>PA - Pennsylvania</OPTION>
<OPTION CLASS=Region1 VALUE="PR" <% if SVALUE = "PR" then response.write "SELECTED" %>>PR - Puerto Rico</OPTION>
<OPTION CLASS=Region1 VALUE="RI" <% if SVALUE = "RI" then response.write "SELECTED" %>>RI - Rhode Island</OPTION>
<OPTION CLASS=Region1 VALUE="SC" <% if SVALUE = "SC" then response.write "SELECTED" %>>SC - South Carolina</OPTION>
<OPTION CLASS=Region1 VALUE="SD" <% if SVALUE = "SD" then response.write "SELECTED" %>>SD - South Dakota</OPTION>
<OPTION CLASS=Region1 VALUE="TN" <% if SVALUE = "TN" then response.write "SELECTED" %>>TN - Tennessee</OPTION>
<OPTION CLASS=Region1 VALUE="TX" <% if SVALUE = "TX" then response.write "SELECTED" %>>TX - Texas</OPTION>
<OPTION CLASS=Region1 VALUE="UT" <% if SVALUE = "UT" then response.write "SELECTED" %>>UT - Utah</OPTION>
<OPTION CLASS=Region1 VALUE="VT" <% if SVALUE = "VT" then response.write "SELECTED" %>>VT - Vermont</OPTION>
<OPTION CLASS=Region1 VALUE="VA" <% if SVALUE = "VA" then response.write "SELECTED" %>>VA - Virginia</OPTION>
<OPTION CLASS=Region1 VALUE="VI" <% if SVALUE = "VI" then response.write "SELECTED" %>>VI - US Virgin Islands</OPTION>
<OPTION CLASS=Region1 VALUE="WA" <% if SVALUE = "WA" then response.write "SELECTED" %>>WA - Washington</OPTION>
<OPTION CLASS=Region1 VALUE="WV" <% if SVALUE = "WV" then response.write "SELECTED" %>>WV - West Virginia</OPTION>
<OPTION CLASS=Region1 VALUE="WI" <% if SVALUE = "WI" then response.write "SELECTED" %>>WI - Wisconsin</OPTION>
<OPTION CLASS=Region1 VALUE="WY" <% if SVALUE = "WY" then response.write "SELECTED" %>>WY - Wyoming</OPTION>
<OPTION VALUE=""></OPTION>
<OPTION CLASS=NavLeftHighlight1 VALUE="">-- Canada</OPTION>
<OPTION CLASS=Region3 VALUE="AB" <% if SVALUE = "AB" then response.write "SELECTED" %>>AB - Alberta</OPTION>
<OPTION CLASS=Region3 VALUE="BC" <% if SVALUE = "BC" then response.write "SELECTED" %>>BC - British Columbia</OPTION>
<OPTION CLASS=Region3 VALUE="MB" <% if SVALUE = "MB" then response.write "SELECTED" %>>MB - Manitoba</OPTION>
<OPTION CLASS=Region3 VALUE="NB" <% if SVALUE = "NB" then response.write "SELECTED" %>>NB - New Brunswick</OPTION>
<OPTION CLASS=Region3 VALUE="NF" <% if SVALUE = "NF" then response.write "SELECTED" %>>NF - Newfoundland</OPTION>
<OPTION CLASS=Region3 VALUE="NT" <% if SVALUE = "NT" then response.write "SELECTED" %>>NT - Northern Territory</OPTION>
<OPTION CLASS=Region3 VALUE="NS" <% if SVALUE = "NS" then response.write "SELECTED" %>>NS - Nova Scotia</OPTION>
<OPTION CLASS=Region3 VALUE="ON" <% if SVALUE = "ON" then response.write "SELECTED" %>>ON - Ontario</OPTION>
<OPTION CLASS=Region3 VALUE="PE" <% if SVALUE = "PE" then response.write "SELECTED" %>>PE - Prince Edward Island</OPTION>
<OPTION CLASS=Region3 VALUE="PQ" <% if SVALUE = "PQ" then response.write "SELECTED" %>>PQ - Quebec</OPTION>
<OPTION CLASS=Region3 VALUE="SK" <% if SVALUE = "SK" then response.write "SELECTED" %>>SK - Saskatchewan</OPTION>
<OPTION CLASS=Region3 VALUE="YT" <% if SVALUE = "YT" then response.write "SELECTED" %>>YT - Yukon Territory</OPTION>
